# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5edf20a96aa9824fec154c0a0e314dc5"
name = "gobbl-ai-chatbot"
handle = "gobbl-ai-chatbot-1"
application_url = "https://dispatch-reconstruction-maintain-dating.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dispatch-reconstruction-maintain-dating.trycloudflare.com/auth/callback",
  "https://dispatch-reconstruction-maintain-dating.trycloudflare.com/auth/shopify/callback",
  "https://dispatch-reconstruction-maintain-dating.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
