# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "53e8ddc5e5f7a441b5c5144cf7788d02"
name = "Gobbl AI Chatbot"
handle = "new-app-1012"
application_url = "https://gobbl-chatbot.fly.dev/"
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,read_themes,write_customers,write_products,write_script_tags,write_themes,write_cart_transforms"

[auth]
redirect_urls = [
  "https://gobbl-chatbot.fly.dev/auth/callback",
  "https://gobbl-chatbot.fly.dev/auth/shopify/callback",
  "https://gobbl-chatbot.fly.dev/api/auth/callback"
]

[pos]
embedded = false
